package kerberos.tickets;

/**
 * Class to represent a ticket generated by a server that a client uses to
 * authenticate to other servers.
 */
public class Ticket {

	private String clientID;
	private String clientAddress;
	private String endTime;
	private String sessionKey;

	public Ticket(String clientID, String clientAddress, String endTime,
			String sessionKey) {
		this.clientID = clientID;
		this.clientAddress = clientAddress;
		this.endTime = endTime;
		this.sessionKey = sessionKey;

	}

	public String getClientID() {
		return clientID;
	}

	public String getClientAddress() {
		return clientAddress;
	}

	public String getEndTime() {
		return endTime;
	}

	public String getSessionKey() {
		return sessionKey;
	}

}
